title: Harmanpreet Kaur
logo: logo1.png
#description: A passionate and data-driven individual dedicated to leveraging insights to drive meaningful decisions with 6 years of experience in Retail, Wholesale, and Finance Domains.
#show_downloads: false
theme: jekyll-theme-minimal
